# -*- coding: utf-8 -*-
"""Cost Comparision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tLjpzrc208YnLL-hqsmv1RkYU7U79cOU
"""

import matplotlib.pyplot as plt

# Data
methods = ['Efficient Code', 'Inefficient Code', 'Python Code', 'Java Code']
costs_usd = [
    3.413508e-14,   # Efficient Code
    4.7964e-14,     # Inefficient Code
    1.62e-9,        # Python Code
    3.35e-13        # Java Code
]

# Create a bar chart
plt.figure(figsize=(8, 5))
plt.bar(methods, costs_usd, color=['green', 'red', 'blue', 'purple'])
plt.xlabel('Code Method')
plt.ylabel('Cost (USD)')
plt.title('Cost Comparison for Different Code Implementations')
plt.yscale('log')  # Log scale for better visualization
plt.show()